// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: ingestion/v1/ingestion.proto

package ingestionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Channel messages
type Channel struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	YoutubeChannelId string                 `protobuf:"bytes,2,opt,name=youtube_channel_id,json=youtubeChannelId,proto3" json:"youtube_channel_id,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ThumbnailUrl     string                 `protobuf:"bytes,4,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Subscribed       bool                   `protobuf:"varint,5,opt,name=subscribed,proto3" json:"subscribed,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *Channel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Channel) GetYoutubeChannelId() string {
	if x != nil {
		return x.YoutubeChannelId
	}
	return ""
}

func (x *Channel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Channel) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Channel) GetSubscribed() bool {
	if x != nil {
		return x.Subscribed
	}
	return false
}

func (x *Channel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Channel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Channel) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type GetChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelRequest) Reset() {
	*x = GetChannelRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelRequest) ProtoMessage() {}

func (x *GetChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelRequest.ProtoReflect.Descriptor instead.
func (*GetChannelRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *GetChannelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelResponse) Reset() {
	*x = GetChannelResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelResponse) ProtoMessage() {}

func (x *GetChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelResponse.ProtoReflect.Descriptor instead.
func (*GetChannelResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *GetChannelResponse) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type ListChannelsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscribedOnly bool                   `protobuf:"varint,1,opt,name=subscribed_only,json=subscribedOnly,proto3" json:"subscribed_only,omitempty"`
	Query          string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	PageSize       int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset() {
	*x = ListChannelsRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsRequest) ProtoMessage() {}

func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{3}
}

func (x *ListChannelsRequest) GetSubscribedOnly() bool {
	if x != nil {
		return x.SubscribedOnly
	}
	return false
}

func (x *ListChannelsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListChannelsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListChannelsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*Channel             `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset() {
	*x = ListChannelsResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResponse) ProtoMessage() {}

func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{4}
}

func (x *ListChannelsResponse) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *ListChannelsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListChannelsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type SubscribeChannelRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	YoutubeChannelId string                 `protobuf:"bytes,1,opt,name=youtube_channel_id,json=youtubeChannelId,proto3" json:"youtube_channel_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscribeChannelRequest) Reset() {
	*x = SubscribeChannelRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeChannelRequest) ProtoMessage() {}

func (x *SubscribeChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeChannelRequest.ProtoReflect.Descriptor instead.
func (*SubscribeChannelRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeChannelRequest) GetYoutubeChannelId() string {
	if x != nil {
		return x.YoutubeChannelId
	}
	return ""
}

type SubscribeChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeChannelResponse) Reset() {
	*x = SubscribeChannelResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeChannelResponse) ProtoMessage() {}

func (x *SubscribeChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeChannelResponse.ProtoReflect.Descriptor instead.
func (*SubscribeChannelResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeChannelResponse) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type UnsubscribeChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeChannelRequest) Reset() {
	*x = UnsubscribeChannelRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeChannelRequest) ProtoMessage() {}

func (x *UnsubscribeChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeChannelRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeChannelRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{7}
}

func (x *UnsubscribeChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type UnsubscribeChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeChannelResponse) Reset() {
	*x = UnsubscribeChannelResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeChannelResponse) ProtoMessage() {}

func (x *UnsubscribeChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeChannelResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeChannelResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{8}
}

func (x *UnsubscribeChannelResponse) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

// Video messages
type Video struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	YoutubeVideoId   string                 `protobuf:"bytes,2,opt,name=youtube_video_id,json=youtubeVideoId,proto3" json:"youtube_video_id,omitempty"`
	YoutubeChannelId string                 `protobuf:"bytes,3,opt,name=youtube_channel_id,json=youtubeChannelId,proto3" json:"youtube_channel_id,omitempty"`
	Title            string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	ThumbnailUrl     string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	PublishedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CategoryId       int32                  `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{9}
}

func (x *Video) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Video) GetYoutubeVideoId() string {
	if x != nil {
		return x.YoutubeVideoId
	}
	return ""
}

func (x *Video) GetYoutubeChannelId() string {
	if x != nil {
		return x.YoutubeChannelId
	}
	return ""
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Video) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Video) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Video) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Video) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Video) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type GetVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoRequest) Reset() {
	*x = GetVideoRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoRequest) ProtoMessage() {}

func (x *GetVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{10}
}

func (x *GetVideoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *Video                 `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoResponse) Reset() {
	*x = GetVideoResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoResponse) ProtoMessage() {}

func (x *GetVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoResponse.ProtoReflect.Descriptor instead.
func (*GetVideoResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{11}
}

func (x *GetVideoResponse) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

type ListVideosRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChannelId      string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PublishedAfter *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=published_after,json=publishedAfter,proto3" json:"published_after,omitempty"`
	PageSize       int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListVideosRequest) Reset() {
	*x = ListVideosRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosRequest) ProtoMessage() {}

func (x *ListVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosRequest.ProtoReflect.Descriptor instead.
func (*ListVideosRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{12}
}

func (x *ListVideosRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ListVideosRequest) GetPublishedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAfter
	}
	return nil
}

func (x *ListVideosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListVideosRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*Video               `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosResponse) Reset() {
	*x = ListVideosResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosResponse) ProtoMessage() {}

func (x *ListVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosResponse.ProtoReflect.Descriptor instead.
func (*ListVideosResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{13}
}

func (x *ListVideosResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListVideosResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListVideosResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CollectTrendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionCode    string                 `protobuf:"bytes,1,opt,name=region_code,json=regionCode,proto3" json:"region_code,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectTrendingRequest) Reset() {
	*x = CollectTrendingRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectTrendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectTrendingRequest) ProtoMessage() {}

func (x *CollectTrendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectTrendingRequest.ProtoReflect.Descriptor instead.
func (*CollectTrendingRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{14}
}

func (x *CollectTrendingRequest) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *CollectTrendingRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type CollectTrendingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VideosProcessed int32                  `protobuf:"varint,1,opt,name=videos_processed,json=videosProcessed,proto3" json:"videos_processed,omitempty"`
	VideosAdded     int32                  `protobuf:"varint,2,opt,name=videos_added,json=videosAdded,proto3" json:"videos_added,omitempty"`
	DurationMs      int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CollectTrendingResponse) Reset() {
	*x = CollectTrendingResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectTrendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectTrendingResponse) ProtoMessage() {}

func (x *CollectTrendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectTrendingResponse.ProtoReflect.Descriptor instead.
func (*CollectTrendingResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{15}
}

func (x *CollectTrendingResponse) GetVideosProcessed() int32 {
	if x != nil {
		return x.VideosProcessed
	}
	return 0
}

func (x *CollectTrendingResponse) GetVideosAdded() int32 {
	if x != nil {
		return x.VideosAdded
	}
	return 0
}

func (x *CollectTrendingResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type CollectSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectSubscriptionsRequest) Reset() {
	*x = CollectSubscriptionsRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectSubscriptionsRequest) ProtoMessage() {}

func (x *CollectSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*CollectSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{16}
}

type CollectSubscriptionsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChannelsProcessed int32                  `protobuf:"varint,1,opt,name=channels_processed,json=channelsProcessed,proto3" json:"channels_processed,omitempty"`
	VideosProcessed   int32                  `protobuf:"varint,2,opt,name=videos_processed,json=videosProcessed,proto3" json:"videos_processed,omitempty"`
	VideosAdded       int32                  `protobuf:"varint,3,opt,name=videos_added,json=videosAdded,proto3" json:"videos_added,omitempty"`
	DurationMs        int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CollectSubscriptionsResponse) Reset() {
	*x = CollectSubscriptionsResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectSubscriptionsResponse) ProtoMessage() {}

func (x *CollectSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*CollectSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{17}
}

func (x *CollectSubscriptionsResponse) GetChannelsProcessed() int32 {
	if x != nil {
		return x.ChannelsProcessed
	}
	return 0
}

func (x *CollectSubscriptionsResponse) GetVideosProcessed() int32 {
	if x != nil {
		return x.VideosProcessed
	}
	return 0
}

func (x *CollectSubscriptionsResponse) GetVideosAdded() int32 {
	if x != nil {
		return x.VideosAdded
	}
	return 0
}

func (x *CollectSubscriptionsResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// Snapshot messages
type VideoSnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VideoId           string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	CheckpointHour    int32                  `protobuf:"varint,3,opt,name=checkpoint_hour,json=checkpointHour,proto3" json:"checkpoint_hour,omitempty"`
	MeasuredAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=measured_at,json=measuredAt,proto3" json:"measured_at,omitempty"`
	ViewsCount        int64                  `protobuf:"varint,5,opt,name=views_count,json=viewsCount,proto3" json:"views_count,omitempty"`
	LikesCount        int64                  `protobuf:"varint,6,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	SubscriptionCount int64                  `protobuf:"varint,7,opt,name=subscription_count,json=subscriptionCount,proto3" json:"subscription_count,omitempty"`
	Source            string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VideoSnapshot) Reset() {
	*x = VideoSnapshot{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSnapshot) ProtoMessage() {}

func (x *VideoSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSnapshot.ProtoReflect.Descriptor instead.
func (*VideoSnapshot) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{18}
}

func (x *VideoSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideoSnapshot) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoSnapshot) GetCheckpointHour() int32 {
	if x != nil {
		return x.CheckpointHour
	}
	return 0
}

func (x *VideoSnapshot) GetMeasuredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MeasuredAt
	}
	return nil
}

func (x *VideoSnapshot) GetViewsCount() int64 {
	if x != nil {
		return x.ViewsCount
	}
	return 0
}

func (x *VideoSnapshot) GetLikesCount() int64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *VideoSnapshot) GetSubscriptionCount() int64 {
	if x != nil {
		return x.SubscriptionCount
	}
	return 0
}

func (x *VideoSnapshot) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *VideoSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	CheckpointHour int32                  `protobuf:"varint,2,opt,name=checkpoint_hour,json=checkpointHour,proto3" json:"checkpoint_hour,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{19}
}

func (x *CreateSnapshotRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetCheckpointHour() int32 {
	if x != nil {
		return x.CheckpointHour
	}
	return 0
}

type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *VideoSnapshot         `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{20}
}

func (x *CreateSnapshotResponse) GetSnapshot() *VideoSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type GetSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	CheckpointHour int32                  `protobuf:"varint,2,opt,name=checkpoint_hour,json=checkpointHour,proto3" json:"checkpoint_hour,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{21}
}

func (x *GetSnapshotRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *GetSnapshotRequest) GetCheckpointHour() int32 {
	if x != nil {
		return x.CheckpointHour
	}
	return 0
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *VideoSnapshot         `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{22}
}

func (x *GetSnapshotResponse) GetSnapshot() *VideoSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type ListSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{23}
}

func (x *ListSnapshotsRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*VideoSnapshot       `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{24}
}

func (x *ListSnapshotsResponse) GetSnapshots() []*VideoSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

// System operation messages
type ScheduleSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleSnapshotsRequest) Reset() {
	*x = ScheduleSnapshotsRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleSnapshotsRequest) ProtoMessage() {}

func (x *ScheduleSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ScheduleSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{25}
}

type ScheduleSnapshotsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VideosProcessed int32                  `protobuf:"varint,1,opt,name=videos_processed,json=videosProcessed,proto3" json:"videos_processed,omitempty"`
	TasksScheduled  int32                  `protobuf:"varint,2,opt,name=tasks_scheduled,json=tasksScheduled,proto3" json:"tasks_scheduled,omitempty"`
	DurationMs      int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScheduleSnapshotsResponse) Reset() {
	*x = ScheduleSnapshotsResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleSnapshotsResponse) ProtoMessage() {}

func (x *ScheduleSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ScheduleSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{26}
}

func (x *ScheduleSnapshotsResponse) GetVideosProcessed() int32 {
	if x != nil {
		return x.VideosProcessed
	}
	return 0
}

func (x *ScheduleSnapshotsResponse) GetTasksScheduled() int32 {
	if x != nil {
		return x.TasksScheduled
	}
	return 0
}

func (x *ScheduleSnapshotsResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type UpdateChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelsRequest) Reset() {
	*x = UpdateChannelsRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelsRequest) ProtoMessage() {}

func (x *UpdateChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelsRequest.ProtoReflect.Descriptor instead.
func (*UpdateChannelsRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{27}
}

type UpdateChannelsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChannelsProcessed int32                  `protobuf:"varint,1,opt,name=channels_processed,json=channelsProcessed,proto3" json:"channels_processed,omitempty"`
	ChannelsUpdated   int32                  `protobuf:"varint,2,opt,name=channels_updated,json=channelsUpdated,proto3" json:"channels_updated,omitempty"`
	DurationMs        int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateChannelsResponse) Reset() {
	*x = UpdateChannelsResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelsResponse) ProtoMessage() {}

func (x *UpdateChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelsResponse.ProtoReflect.Descriptor instead.
func (*UpdateChannelsResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateChannelsResponse) GetChannelsProcessed() int32 {
	if x != nil {
		return x.ChannelsProcessed
	}
	return 0
}

func (x *UpdateChannelsResponse) GetChannelsUpdated() int32 {
	if x != nil {
		return x.ChannelsUpdated
	}
	return 0
}

func (x *UpdateChannelsResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// Keyword messages
type Keyword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FilterType    string                 `protobuf:"bytes,3,opt,name=filter_type,json=filterType,proto3" json:"filter_type,omitempty"`
	Pattern       string                 `protobuf:"bytes,4,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keyword) Reset() {
	*x = Keyword{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keyword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keyword) ProtoMessage() {}

func (x *Keyword) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keyword.ProtoReflect.Descriptor instead.
func (*Keyword) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{29}
}

func (x *Keyword) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Keyword) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Keyword) GetFilterType() string {
	if x != nil {
		return x.FilterType
	}
	return ""
}

func (x *Keyword) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Keyword) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Keyword) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Keyword) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetKeywordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeywordRequest) Reset() {
	*x = GetKeywordRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeywordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeywordRequest) ProtoMessage() {}

func (x *GetKeywordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeywordRequest.ProtoReflect.Descriptor instead.
func (*GetKeywordRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{30}
}

func (x *GetKeywordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetKeywordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       *Keyword               `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeywordResponse) Reset() {
	*x = GetKeywordResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeywordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeywordResponse) ProtoMessage() {}

func (x *GetKeywordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeywordResponse.ProtoReflect.Descriptor instead.
func (*GetKeywordResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{31}
}

func (x *GetKeywordResponse) GetKeyword() *Keyword {
	if x != nil {
		return x.Keyword
	}
	return nil
}

type ListKeywordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeywordsRequest) Reset() {
	*x = ListKeywordsRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeywordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeywordsRequest) ProtoMessage() {}

func (x *ListKeywordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeywordsRequest.ProtoReflect.Descriptor instead.
func (*ListKeywordsRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{32}
}

func (x *ListKeywordsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListKeywordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListKeywordsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListKeywordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      []*Keyword             `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeywordsResponse) Reset() {
	*x = ListKeywordsResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeywordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeywordsResponse) ProtoMessage() {}

func (x *ListKeywordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeywordsResponse.ProtoReflect.Descriptor instead.
func (*ListKeywordsResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{33}
}

func (x *ListKeywordsResponse) GetKeywords() []*Keyword {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *ListKeywordsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListKeywordsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateKeywordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FilterType    string                 `protobuf:"bytes,2,opt,name=filter_type,json=filterType,proto3" json:"filter_type,omitempty"`
	Pattern       string                 `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeywordRequest) Reset() {
	*x = CreateKeywordRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeywordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeywordRequest) ProtoMessage() {}

func (x *CreateKeywordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeywordRequest.ProtoReflect.Descriptor instead.
func (*CreateKeywordRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{34}
}

func (x *CreateKeywordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKeywordRequest) GetFilterType() string {
	if x != nil {
		return x.FilterType
	}
	return ""
}

func (x *CreateKeywordRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *CreateKeywordRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateKeywordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       *Keyword               `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeywordResponse) Reset() {
	*x = CreateKeywordResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeywordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeywordResponse) ProtoMessage() {}

func (x *CreateKeywordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeywordResponse.ProtoReflect.Descriptor instead.
func (*CreateKeywordResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{35}
}

func (x *CreateKeywordResponse) GetKeyword() *Keyword {
	if x != nil {
		return x.Keyword
	}
	return nil
}

type UpdateKeywordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FilterType    string                 `protobuf:"bytes,3,opt,name=filter_type,json=filterType,proto3" json:"filter_type,omitempty"`
	Pattern       string                 `protobuf:"bytes,4,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKeywordRequest) Reset() {
	*x = UpdateKeywordRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKeywordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeywordRequest) ProtoMessage() {}

func (x *UpdateKeywordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeywordRequest.ProtoReflect.Descriptor instead.
func (*UpdateKeywordRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{36}
}

func (x *UpdateKeywordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateKeywordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateKeywordRequest) GetFilterType() string {
	if x != nil {
		return x.FilterType
	}
	return ""
}

func (x *UpdateKeywordRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *UpdateKeywordRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateKeywordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       *Keyword               `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKeywordResponse) Reset() {
	*x = UpdateKeywordResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKeywordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeywordResponse) ProtoMessage() {}

func (x *UpdateKeywordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeywordResponse.ProtoReflect.Descriptor instead.
func (*UpdateKeywordResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{37}
}

func (x *UpdateKeywordResponse) GetKeyword() *Keyword {
	if x != nil {
		return x.Keyword
	}
	return nil
}

type DeleteKeywordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeywordRequest) Reset() {
	*x = DeleteKeywordRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeywordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeywordRequest) ProtoMessage() {}

func (x *DeleteKeywordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeywordRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeywordRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{38}
}

func (x *DeleteKeywordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteKeywordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeywordResponse) Reset() {
	*x = DeleteKeywordResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeywordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeywordResponse) ProtoMessage() {}

func (x *DeleteKeywordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeywordResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeywordResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{39}
}

var File_ingestion_v1_ingestion_proto protoreflect.FileDescriptor

const file_ingestion_v1_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x1cingestion/v1/ingestion.proto\x12\fingestion.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd3\x02\n" +
	"\aChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12youtube_channel_id\x18\x02 \x01(\tR\x10youtubeChannelId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12#\n" +
	"\rthumbnail_url\x18\x04 \x01(\tR\fthumbnailUrl\x12\x1e\n" +
	"\n" +
	"subscribed\x18\x05 \x01(\bR\n" +
	"subscribed\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"#\n" +
	"\x11GetChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x12GetChannelResponse\x12/\n" +
	"\achannel\x18\x01 \x01(\v2\x15.ingestion.v1.ChannelR\achannel\"\x90\x01\n" +
	"\x13ListChannelsRequest\x12'\n" +
	"\x0fsubscribed_only\x18\x01 \x01(\bR\x0esubscribedOnly\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x92\x01\n" +
	"\x14ListChannelsResponse\x121\n" +
	"\bchannels\x18\x01 \x03(\v2\x15.ingestion.v1.ChannelR\bchannels\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"G\n" +
	"\x17SubscribeChannelRequest\x12,\n" +
	"\x12youtube_channel_id\x18\x01 \x01(\tR\x10youtubeChannelId\"K\n" +
	"\x18SubscribeChannelResponse\x12/\n" +
	"\achannel\x18\x01 \x01(\v2\x15.ingestion.v1.ChannelR\achannel\":\n" +
	"\x19UnsubscribeChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"M\n" +
	"\x1aUnsubscribeChannelResponse\x12/\n" +
	"\achannel\x18\x01 \x01(\v2\x15.ingestion.v1.ChannelR\achannel\"\xbb\x03\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10youtube_video_id\x18\x02 \x01(\tR\x0eyoutubeVideoId\x12,\n" +
	"\x12youtube_channel_id\x18\x03 \x01(\tR\x10youtubeChannelId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12#\n" +
	"\rthumbnail_url\x18\x05 \x01(\tR\fthumbnailUrl\x12=\n" +
	"\fpublished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\x05R\n" +
	"categoryId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"!\n" +
	"\x0fGetVideoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x10GetVideoResponse\x12)\n" +
	"\x05video\x18\x01 \x01(\v2\x13.ingestion.v1.VideoR\x05video\"\xb3\x01\n" +
	"\x11ListVideosRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12C\n" +
	"\x0fpublished_after\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0epublishedAfter\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x8a\x01\n" +
	"\x12ListVideosResponse\x12+\n" +
	"\x06videos\x18\x01 \x03(\v2\x13.ingestion.v1.VideoR\x06videos\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"Z\n" +
	"\x16CollectTrendingRequest\x12\x1f\n" +
	"\vregion_code\x18\x01 \x01(\tR\n" +
	"regionCode\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x05R\n" +
	"categoryId\"\x88\x01\n" +
	"\x17CollectTrendingResponse\x12)\n" +
	"\x10videos_processed\x18\x01 \x01(\x05R\x0fvideosProcessed\x12!\n" +
	"\fvideos_added\x18\x02 \x01(\x05R\vvideosAdded\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"\x1d\n" +
	"\x1bCollectSubscriptionsRequest\"\xbc\x01\n" +
	"\x1cCollectSubscriptionsResponse\x12-\n" +
	"\x12channels_processed\x18\x01 \x01(\x05R\x11channelsProcessed\x12)\n" +
	"\x10videos_processed\x18\x02 \x01(\x05R\x0fvideosProcessed\x12!\n" +
	"\fvideos_added\x18\x03 \x01(\x05R\vvideosAdded\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\xe4\x02\n" +
	"\rVideoSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12'\n" +
	"\x0fcheckpoint_hour\x18\x03 \x01(\x05R\x0echeckpointHour\x12;\n" +
	"\vmeasured_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"measuredAt\x12\x1f\n" +
	"\vviews_count\x18\x05 \x01(\x03R\n" +
	"viewsCount\x12\x1f\n" +
	"\vlikes_count\x18\x06 \x01(\x03R\n" +
	"likesCount\x12-\n" +
	"\x12subscription_count\x18\a \x01(\x03R\x11subscriptionCount\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"[\n" +
	"\x15CreateSnapshotRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12'\n" +
	"\x0fcheckpoint_hour\x18\x02 \x01(\x05R\x0echeckpointHour\"Q\n" +
	"\x16CreateSnapshotResponse\x127\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1b.ingestion.v1.VideoSnapshotR\bsnapshot\"X\n" +
	"\x12GetSnapshotRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12'\n" +
	"\x0fcheckpoint_hour\x18\x02 \x01(\x05R\x0echeckpointHour\"N\n" +
	"\x13GetSnapshotResponse\x127\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1b.ingestion.v1.VideoSnapshotR\bsnapshot\"1\n" +
	"\x14ListSnapshotsRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"R\n" +
	"\x15ListSnapshotsResponse\x129\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x1b.ingestion.v1.VideoSnapshotR\tsnapshots\"\x1a\n" +
	"\x18ScheduleSnapshotsRequest\"\x90\x01\n" +
	"\x19ScheduleSnapshotsResponse\x12)\n" +
	"\x10videos_processed\x18\x01 \x01(\x05R\x0fvideosProcessed\x12'\n" +
	"\x0ftasks_scheduled\x18\x02 \x01(\x05R\x0etasksScheduled\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"\x17\n" +
	"\x15UpdateChannelsRequest\"\x93\x01\n" +
	"\x16UpdateChannelsResponse\x12-\n" +
	"\x12channels_processed\x18\x01 \x01(\x05R\x11channelsProcessed\x12)\n" +
	"\x10channels_updated\x18\x02 \x01(\x05R\x0fchannelsUpdated\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"\x80\x02\n" +
	"\aKeyword\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vfilter_type\x18\x03 \x01(\tR\n" +
	"filterType\x12\x18\n" +
	"\apattern\x18\x04 \x01(\tR\apattern\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"#\n" +
	"\x11GetKeywordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x12GetKeywordResponse\x12/\n" +
	"\akeyword\x18\x01 \x01(\v2\x15.ingestion.v1.KeywordR\akeyword\"g\n" +
	"\x13ListKeywordsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x92\x01\n" +
	"\x14ListKeywordsResponse\x121\n" +
	"\bkeywords\x18\x01 \x03(\v2\x15.ingestion.v1.KeywordR\bkeywords\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\x87\x01\n" +
	"\x14CreateKeywordRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vfilter_type\x18\x02 \x01(\tR\n" +
	"filterType\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"H\n" +
	"\x15CreateKeywordResponse\x12/\n" +
	"\akeyword\x18\x01 \x01(\v2\x15.ingestion.v1.KeywordR\akeyword\"\x97\x01\n" +
	"\x14UpdateKeywordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vfilter_type\x18\x03 \x01(\tR\n" +
	"filterType\x12\x18\n" +
	"\apattern\x18\x04 \x01(\tR\apattern\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"H\n" +
	"\x15UpdateKeywordResponse\x12/\n" +
	"\akeyword\x18\x01 \x01(\v2\x15.ingestion.v1.KeywordR\akeyword\"&\n" +
	"\x14DeleteKeywordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteKeywordResponse2\xf5\f\n" +
	"\x10IngestionService\x12O\n" +
	"\n" +
	"GetChannel\x12\x1f.ingestion.v1.GetChannelRequest\x1a .ingestion.v1.GetChannelResponse\x12U\n" +
	"\fListChannels\x12!.ingestion.v1.ListChannelsRequest\x1a\".ingestion.v1.ListChannelsResponse\x12a\n" +
	"\x10SubscribeChannel\x12%.ingestion.v1.SubscribeChannelRequest\x1a&.ingestion.v1.SubscribeChannelResponse\x12g\n" +
	"\x12UnsubscribeChannel\x12'.ingestion.v1.UnsubscribeChannelRequest\x1a(.ingestion.v1.UnsubscribeChannelResponse\x12I\n" +
	"\bGetVideo\x12\x1d.ingestion.v1.GetVideoRequest\x1a\x1e.ingestion.v1.GetVideoResponse\x12O\n" +
	"\n" +
	"ListVideos\x12\x1f.ingestion.v1.ListVideosRequest\x1a .ingestion.v1.ListVideosResponse\x12^\n" +
	"\x0fCollectTrending\x12$.ingestion.v1.CollectTrendingRequest\x1a%.ingestion.v1.CollectTrendingResponse\x12m\n" +
	"\x14CollectSubscriptions\x12).ingestion.v1.CollectSubscriptionsRequest\x1a*.ingestion.v1.CollectSubscriptionsResponse\x12[\n" +
	"\x0eCreateSnapshot\x12#.ingestion.v1.CreateSnapshotRequest\x1a$.ingestion.v1.CreateSnapshotResponse\x12R\n" +
	"\vGetSnapshot\x12 .ingestion.v1.GetSnapshotRequest\x1a!.ingestion.v1.GetSnapshotResponse\x12X\n" +
	"\rListSnapshots\x12\".ingestion.v1.ListSnapshotsRequest\x1a#.ingestion.v1.ListSnapshotsResponse\x12O\n" +
	"\n" +
	"GetKeyword\x12\x1f.ingestion.v1.GetKeywordRequest\x1a .ingestion.v1.GetKeywordResponse\x12U\n" +
	"\fListKeywords\x12!.ingestion.v1.ListKeywordsRequest\x1a\".ingestion.v1.ListKeywordsResponse\x12X\n" +
	"\rCreateKeyword\x12\".ingestion.v1.CreateKeywordRequest\x1a#.ingestion.v1.CreateKeywordResponse\x12X\n" +
	"\rUpdateKeyword\x12\".ingestion.v1.UpdateKeywordRequest\x1a#.ingestion.v1.UpdateKeywordResponse\x12X\n" +
	"\rDeleteKeyword\x12\".ingestion.v1.DeleteKeywordRequest\x1a#.ingestion.v1.DeleteKeywordResponse\x12d\n" +
	"\x11ScheduleSnapshots\x12&.ingestion.v1.ScheduleSnapshotsRequest\x1a'.ingestion.v1.ScheduleSnapshotsResponse\x12[\n" +
	"\x0eUpdateChannels\x12#.ingestion.v1.UpdateChannelsRequest\x1a$.ingestion.v1.UpdateChannelsResponseBLZJgithub.com/YukiOnishi1129/youtube-analytics/proto/ingestion/v1;ingestionv1b\x06proto3"

var (
	file_ingestion_v1_ingestion_proto_rawDescOnce sync.Once
	file_ingestion_v1_ingestion_proto_rawDescData []byte
)

func file_ingestion_v1_ingestion_proto_rawDescGZIP() []byte {
	file_ingestion_v1_ingestion_proto_rawDescOnce.Do(func() {
		file_ingestion_v1_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestion_v1_ingestion_proto_rawDesc), len(file_ingestion_v1_ingestion_proto_rawDesc)))
	})
	return file_ingestion_v1_ingestion_proto_rawDescData
}

var file_ingestion_v1_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_ingestion_v1_ingestion_proto_goTypes = []any{
	(*Channel)(nil),                      // 0: ingestion.v1.Channel
	(*GetChannelRequest)(nil),            // 1: ingestion.v1.GetChannelRequest
	(*GetChannelResponse)(nil),           // 2: ingestion.v1.GetChannelResponse
	(*ListChannelsRequest)(nil),          // 3: ingestion.v1.ListChannelsRequest
	(*ListChannelsResponse)(nil),         // 4: ingestion.v1.ListChannelsResponse
	(*SubscribeChannelRequest)(nil),      // 5: ingestion.v1.SubscribeChannelRequest
	(*SubscribeChannelResponse)(nil),     // 6: ingestion.v1.SubscribeChannelResponse
	(*UnsubscribeChannelRequest)(nil),    // 7: ingestion.v1.UnsubscribeChannelRequest
	(*UnsubscribeChannelResponse)(nil),   // 8: ingestion.v1.UnsubscribeChannelResponse
	(*Video)(nil),                        // 9: ingestion.v1.Video
	(*GetVideoRequest)(nil),              // 10: ingestion.v1.GetVideoRequest
	(*GetVideoResponse)(nil),             // 11: ingestion.v1.GetVideoResponse
	(*ListVideosRequest)(nil),            // 12: ingestion.v1.ListVideosRequest
	(*ListVideosResponse)(nil),           // 13: ingestion.v1.ListVideosResponse
	(*CollectTrendingRequest)(nil),       // 14: ingestion.v1.CollectTrendingRequest
	(*CollectTrendingResponse)(nil),      // 15: ingestion.v1.CollectTrendingResponse
	(*CollectSubscriptionsRequest)(nil),  // 16: ingestion.v1.CollectSubscriptionsRequest
	(*CollectSubscriptionsResponse)(nil), // 17: ingestion.v1.CollectSubscriptionsResponse
	(*VideoSnapshot)(nil),                // 18: ingestion.v1.VideoSnapshot
	(*CreateSnapshotRequest)(nil),        // 19: ingestion.v1.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),       // 20: ingestion.v1.CreateSnapshotResponse
	(*GetSnapshotRequest)(nil),           // 21: ingestion.v1.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),          // 22: ingestion.v1.GetSnapshotResponse
	(*ListSnapshotsRequest)(nil),         // 23: ingestion.v1.ListSnapshotsRequest
	(*ListSnapshotsResponse)(nil),        // 24: ingestion.v1.ListSnapshotsResponse
	(*ScheduleSnapshotsRequest)(nil),     // 25: ingestion.v1.ScheduleSnapshotsRequest
	(*ScheduleSnapshotsResponse)(nil),    // 26: ingestion.v1.ScheduleSnapshotsResponse
	(*UpdateChannelsRequest)(nil),        // 27: ingestion.v1.UpdateChannelsRequest
	(*UpdateChannelsResponse)(nil),       // 28: ingestion.v1.UpdateChannelsResponse
	(*Keyword)(nil),                      // 29: ingestion.v1.Keyword
	(*GetKeywordRequest)(nil),            // 30: ingestion.v1.GetKeywordRequest
	(*GetKeywordResponse)(nil),           // 31: ingestion.v1.GetKeywordResponse
	(*ListKeywordsRequest)(nil),          // 32: ingestion.v1.ListKeywordsRequest
	(*ListKeywordsResponse)(nil),         // 33: ingestion.v1.ListKeywordsResponse
	(*CreateKeywordRequest)(nil),         // 34: ingestion.v1.CreateKeywordRequest
	(*CreateKeywordResponse)(nil),        // 35: ingestion.v1.CreateKeywordResponse
	(*UpdateKeywordRequest)(nil),         // 36: ingestion.v1.UpdateKeywordRequest
	(*UpdateKeywordResponse)(nil),        // 37: ingestion.v1.UpdateKeywordResponse
	(*DeleteKeywordRequest)(nil),         // 38: ingestion.v1.DeleteKeywordRequest
	(*DeleteKeywordResponse)(nil),        // 39: ingestion.v1.DeleteKeywordResponse
	(*timestamppb.Timestamp)(nil),        // 40: google.protobuf.Timestamp
}
var file_ingestion_v1_ingestion_proto_depIdxs = []int32{
	40, // 0: ingestion.v1.Channel.created_at:type_name -> google.protobuf.Timestamp
	40, // 1: ingestion.v1.Channel.updated_at:type_name -> google.protobuf.Timestamp
	40, // 2: ingestion.v1.Channel.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: ingestion.v1.GetChannelResponse.channel:type_name -> ingestion.v1.Channel
	0,  // 4: ingestion.v1.ListChannelsResponse.channels:type_name -> ingestion.v1.Channel
	0,  // 5: ingestion.v1.SubscribeChannelResponse.channel:type_name -> ingestion.v1.Channel
	0,  // 6: ingestion.v1.UnsubscribeChannelResponse.channel:type_name -> ingestion.v1.Channel
	40, // 7: ingestion.v1.Video.published_at:type_name -> google.protobuf.Timestamp
	40, // 8: ingestion.v1.Video.created_at:type_name -> google.protobuf.Timestamp
	40, // 9: ingestion.v1.Video.updated_at:type_name -> google.protobuf.Timestamp
	40, // 10: ingestion.v1.Video.deleted_at:type_name -> google.protobuf.Timestamp
	9,  // 11: ingestion.v1.GetVideoResponse.video:type_name -> ingestion.v1.Video
	40, // 12: ingestion.v1.ListVideosRequest.published_after:type_name -> google.protobuf.Timestamp
	9,  // 13: ingestion.v1.ListVideosResponse.videos:type_name -> ingestion.v1.Video
	40, // 14: ingestion.v1.VideoSnapshot.measured_at:type_name -> google.protobuf.Timestamp
	40, // 15: ingestion.v1.VideoSnapshot.created_at:type_name -> google.protobuf.Timestamp
	18, // 16: ingestion.v1.CreateSnapshotResponse.snapshot:type_name -> ingestion.v1.VideoSnapshot
	18, // 17: ingestion.v1.GetSnapshotResponse.snapshot:type_name -> ingestion.v1.VideoSnapshot
	18, // 18: ingestion.v1.ListSnapshotsResponse.snapshots:type_name -> ingestion.v1.VideoSnapshot
	40, // 19: ingestion.v1.Keyword.created_at:type_name -> google.protobuf.Timestamp
	40, // 20: ingestion.v1.Keyword.updated_at:type_name -> google.protobuf.Timestamp
	29, // 21: ingestion.v1.GetKeywordResponse.keyword:type_name -> ingestion.v1.Keyword
	29, // 22: ingestion.v1.ListKeywordsResponse.keywords:type_name -> ingestion.v1.Keyword
	29, // 23: ingestion.v1.CreateKeywordResponse.keyword:type_name -> ingestion.v1.Keyword
	29, // 24: ingestion.v1.UpdateKeywordResponse.keyword:type_name -> ingestion.v1.Keyword
	1,  // 25: ingestion.v1.IngestionService.GetChannel:input_type -> ingestion.v1.GetChannelRequest
	3,  // 26: ingestion.v1.IngestionService.ListChannels:input_type -> ingestion.v1.ListChannelsRequest
	5,  // 27: ingestion.v1.IngestionService.SubscribeChannel:input_type -> ingestion.v1.SubscribeChannelRequest
	7,  // 28: ingestion.v1.IngestionService.UnsubscribeChannel:input_type -> ingestion.v1.UnsubscribeChannelRequest
	10, // 29: ingestion.v1.IngestionService.GetVideo:input_type -> ingestion.v1.GetVideoRequest
	12, // 30: ingestion.v1.IngestionService.ListVideos:input_type -> ingestion.v1.ListVideosRequest
	14, // 31: ingestion.v1.IngestionService.CollectTrending:input_type -> ingestion.v1.CollectTrendingRequest
	16, // 32: ingestion.v1.IngestionService.CollectSubscriptions:input_type -> ingestion.v1.CollectSubscriptionsRequest
	19, // 33: ingestion.v1.IngestionService.CreateSnapshot:input_type -> ingestion.v1.CreateSnapshotRequest
	21, // 34: ingestion.v1.IngestionService.GetSnapshot:input_type -> ingestion.v1.GetSnapshotRequest
	23, // 35: ingestion.v1.IngestionService.ListSnapshots:input_type -> ingestion.v1.ListSnapshotsRequest
	30, // 36: ingestion.v1.IngestionService.GetKeyword:input_type -> ingestion.v1.GetKeywordRequest
	32, // 37: ingestion.v1.IngestionService.ListKeywords:input_type -> ingestion.v1.ListKeywordsRequest
	34, // 38: ingestion.v1.IngestionService.CreateKeyword:input_type -> ingestion.v1.CreateKeywordRequest
	36, // 39: ingestion.v1.IngestionService.UpdateKeyword:input_type -> ingestion.v1.UpdateKeywordRequest
	38, // 40: ingestion.v1.IngestionService.DeleteKeyword:input_type -> ingestion.v1.DeleteKeywordRequest
	25, // 41: ingestion.v1.IngestionService.ScheduleSnapshots:input_type -> ingestion.v1.ScheduleSnapshotsRequest
	27, // 42: ingestion.v1.IngestionService.UpdateChannels:input_type -> ingestion.v1.UpdateChannelsRequest
	2,  // 43: ingestion.v1.IngestionService.GetChannel:output_type -> ingestion.v1.GetChannelResponse
	4,  // 44: ingestion.v1.IngestionService.ListChannels:output_type -> ingestion.v1.ListChannelsResponse
	6,  // 45: ingestion.v1.IngestionService.SubscribeChannel:output_type -> ingestion.v1.SubscribeChannelResponse
	8,  // 46: ingestion.v1.IngestionService.UnsubscribeChannel:output_type -> ingestion.v1.UnsubscribeChannelResponse
	11, // 47: ingestion.v1.IngestionService.GetVideo:output_type -> ingestion.v1.GetVideoResponse
	13, // 48: ingestion.v1.IngestionService.ListVideos:output_type -> ingestion.v1.ListVideosResponse
	15, // 49: ingestion.v1.IngestionService.CollectTrending:output_type -> ingestion.v1.CollectTrendingResponse
	17, // 50: ingestion.v1.IngestionService.CollectSubscriptions:output_type -> ingestion.v1.CollectSubscriptionsResponse
	20, // 51: ingestion.v1.IngestionService.CreateSnapshot:output_type -> ingestion.v1.CreateSnapshotResponse
	22, // 52: ingestion.v1.IngestionService.GetSnapshot:output_type -> ingestion.v1.GetSnapshotResponse
	24, // 53: ingestion.v1.IngestionService.ListSnapshots:output_type -> ingestion.v1.ListSnapshotsResponse
	31, // 54: ingestion.v1.IngestionService.GetKeyword:output_type -> ingestion.v1.GetKeywordResponse
	33, // 55: ingestion.v1.IngestionService.ListKeywords:output_type -> ingestion.v1.ListKeywordsResponse
	35, // 56: ingestion.v1.IngestionService.CreateKeyword:output_type -> ingestion.v1.CreateKeywordResponse
	37, // 57: ingestion.v1.IngestionService.UpdateKeyword:output_type -> ingestion.v1.UpdateKeywordResponse
	39, // 58: ingestion.v1.IngestionService.DeleteKeyword:output_type -> ingestion.v1.DeleteKeywordResponse
	26, // 59: ingestion.v1.IngestionService.ScheduleSnapshots:output_type -> ingestion.v1.ScheduleSnapshotsResponse
	28, // 60: ingestion.v1.IngestionService.UpdateChannels:output_type -> ingestion.v1.UpdateChannelsResponse
	43, // [43:61] is the sub-list for method output_type
	25, // [25:43] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_ingestion_v1_ingestion_proto_init() }
func file_ingestion_v1_ingestion_proto_init() {
	if File_ingestion_v1_ingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_v1_ingestion_proto_rawDesc), len(file_ingestion_v1_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingestion_v1_ingestion_proto_goTypes,
		DependencyIndexes: file_ingestion_v1_ingestion_proto_depIdxs,
		MessageInfos:      file_ingestion_v1_ingestion_proto_msgTypes,
	}.Build()
	File_ingestion_v1_ingestion_proto = out.File
	file_ingestion_v1_ingestion_proto_goTypes = nil
	file_ingestion_v1_ingestion_proto_depIdxs = nil
}
