// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"

	"github.com/google/uuid"
)

type AuthorityAccount struct {
	ID            uuid.UUID      `json:"id"`
	Email         string         `json:"email"`
	EmailVerified sql.NullBool   `json:"email_verified"`
	DisplayName   sql.NullString `json:"display_name"`
	PhotoUrl      sql.NullString `json:"photo_url"`
	IsActive      sql.NullBool   `json:"is_active"`
	LastLoginAt   sql.NullTime   `json:"last_login_at"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
}

type AuthorityAccountIdentity struct {
	ID          uuid.UUID      `json:"id"`
	AccountID   uuid.UUID      `json:"account_id"`
	Provider    string         `json:"provider"`
	ProviderUid sql.NullString `json:"provider_uid"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type AuthorityAccountRole struct {
	AccountID uuid.UUID    `json:"account_id"`
	RoleID    uuid.UUID    `json:"role_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type AuthorityRole struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}
