// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignRole(ctx context.Context, arg AssignRoleParams) error
	DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) error
	FindAccountByProvider(ctx context.Context, arg FindAccountByProviderParams) (FindAccountByProviderRow, error)
	GetAccountByEmail(ctx context.Context, email string) (GetAccountByEmailRow, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error)
	ListIdentitiesByAccount(ctx context.Context, accountID uuid.UUID) ([]ListIdentitiesByAccountRow, error)
	ListRolesByAccount(ctx context.Context, accountID uuid.UUID) ([]string, error)
	RevokeRole(ctx context.Context, arg RevokeRoleParams) error
	UpsertAccount(ctx context.Context, arg UpsertAccountParams) error
	UpsertIdentity(ctx context.Context, arg UpsertIdentityParams) error
}

var _ Querier = (*Queries)(nil)
