// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: proto/ingestion/v1/ingestion.proto

package ingestionv1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Channel represents a YouTube channel
type Channel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	YoutubeChannelId string                 `protobuf:"bytes,2,opt,name=youtube_channel_id,json=youtubeChannelId,proto3" json:"youtube_channel_id,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ThumbnailUrl     string                 `protobuf:"bytes,4,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Subscribed       bool                   `protobuf:"varint,5,opt,name=subscribed,proto3" json:"subscribed,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *Channel) Reset() {
	*x = Channel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ingestion_v1_ingestion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingestion_v1_ingestion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_proto_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *Channel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Channel) GetYoutubeChannelId() string {
	if x != nil {
		return x.YoutubeChannelId
	}
	return ""
}

func (x *Channel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Channel) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Channel) GetSubscribed() bool {
	if x != nil {
		return x.Subscribed
	}
	return false
}

func (x *Channel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Channel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Channel) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// Video represents a YouTube video
type Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	YoutubeVideoId   string                 `protobuf:"bytes,2,opt,name=youtube_video_id,json=youtubeVideoId,proto3" json:"youtube_video_id,omitempty"`
	YoutubeChannelId string                 `protobuf:"bytes,3,opt,name=youtube_channel_id,json=youtubeChannelId,proto3" json:"youtube_channel_id,omitempty"`
	Title            string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	ThumbnailUrl     string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	PublishedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CategoryId       int32                  `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *Video) Reset() {
	*x = Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ingestion_v1_ingestion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingestion_v1_ingestion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_proto_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *Video) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Video) GetYoutubeVideoId() string {
	if x != nil {
		return x.YoutubeVideoId
	}
	return ""
}

func (x *Video) GetYoutubeChannelId() string {
	if x != nil {
		return x.YoutubeChannelId
	}
	return ""
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Video) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Video) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Video) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Video) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Video) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// VideoSnapshot represents a video statistics snapshot
type VideoSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VideoId           string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	CheckpointHour    int32                  `protobuf:"varint,3,opt,name=checkpoint_hour,json=checkpointHour,proto3" json:"checkpoint_hour,omitempty"`
	MeasuredAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=measured_at,json=measuredAt,proto3" json:"measured_at,omitempty"`
	ViewsCount        int64                  `protobuf:"varint,5,opt,name=views_count,json=viewsCount,proto3" json:"views_count,omitempty"`
	LikesCount        int64                  `protobuf:"varint,6,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	SubscriptionCount int64                  `protobuf:"varint,7,opt,name=subscription_count,json=subscriptionCount,proto3" json:"subscription_count,omitempty"`
	Source            string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *VideoSnapshot) Reset() {
	*x = VideoSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ingestion_v1_ingestion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSnapshot) ProtoMessage() {}

func (x *VideoSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingestion_v1_ingestion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSnapshot.ProtoReflect.Descriptor instead.
func (*VideoSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *VideoSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideoSnapshot) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoSnapshot) GetCheckpointHour() int32 {
	if x != nil {
		return x.CheckpointHour
	}
	return 0
}

func (x *VideoSnapshot) GetMeasuredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MeasuredAt
	}
	return nil
}

func (x *VideoSnapshot) GetViewsCount() int64 {
	if x != nil {
		return x.ViewsCount
	}
	return 0
}

func (x *VideoSnapshot) GetLikesCount() int64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *VideoSnapshot) GetSubscriptionCount() int64 {
	if x != nil {
		return x.SubscriptionCount
	}
	return 0
}

func (x *VideoSnapshot) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *VideoSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_ingestion_v1_ingestion_proto protoreflect.FileDescriptor

var file_proto_ingestion_v1_ingestion_proto_rawDesc = []byte{
	// Proto file bytes would go here - omitted for brevity
}

var (
	file_proto_ingestion_v1_ingestion_proto_rawDescOnce sync.Once
	file_proto_ingestion_v1_ingestion_proto_rawDescData = file_proto_ingestion_v1_ingestion_proto_rawDesc
)

func file_proto_ingestion_v1_ingestion_proto_rawDescGZIP() []byte {
	file_proto_ingestion_v1_ingestion_proto_rawDescOnce.Do(func() {
		file_proto_ingestion_v1_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ingestion_v1_ingestion_proto_rawDescData)
	})
	return file_proto_ingestion_v1_ingestion_proto_rawDescData
}

var file_proto_ingestion_v1_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_ingestion_v1_ingestion_proto_goTypes = []interface{}{
	(*Channel)(nil),               // 0: ingestion.v1.Channel
	(*Video)(nil),                 // 1: ingestion.v1.Video
	(*VideoSnapshot)(nil),         // 2: ingestion.v1.VideoSnapshot
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}

var file_proto_ingestion_v1_ingestion_proto_depIdxs = []int32{
	3, // 0: ingestion.v1.Channel.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: ingestion.v1.Channel.updated_at:type_name -> google.protobuf.Timestamp
	3, // 2: ingestion.v1.Channel.deleted_at:type_name -> google.protobuf.Timestamp
	3, // 3: ingestion.v1.Video.published_at:type_name -> google.protobuf.Timestamp
	3, // 4: ingestion.v1.Video.created_at:type_name -> google.protobuf.Timestamp
	3, // 5: ingestion.v1.Video.updated_at:type_name -> google.protobuf.Timestamp
	3, // 6: ingestion.v1.Video.deleted_at:type_name -> google.protobuf.Timestamp
	3, // 7: ingestion.v1.VideoSnapshot.measured_at:type_name -> google.protobuf.Timestamp
	3, // 8: ingestion.v1.VideoSnapshot.created_at:type_name -> google.protobuf.Timestamp
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_ingestion_v1_ingestion_proto_init() }
func file_proto_ingestion_v1_ingestion_proto_init() {
	if File_proto_ingestion_v1_ingestion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ingestion_v1_ingestion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Channel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ingestion_v1_ingestion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ingestion_v1_ingestion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ingestion_v1_ingestion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ingestion_v1_ingestion_proto_goTypes,
		DependencyIndexes: file_proto_ingestion_v1_ingestion_proto_depIdxs,
		MessageInfos:      file_proto_ingestion_v1_ingestion_proto_msgTypes,
	}.Build()
	File_proto_ingestion_v1_ingestion_proto = out.File
	file_proto_ingestion_v1_ingestion_proto_rawDesc = nil
	file_proto_ingestion_v1_ingestion_proto_goTypes = nil
	file_proto_ingestion_v1_ingestion_proto_depIdxs = nil
}
