// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type IngestionChannel struct {
	ID               uuid.UUID    `json:"id"`
	YoutubeChannelID string       `json:"youtube_channel_id"`
	Title            string       `json:"title"`
	ThumbnailUrl     string       `json:"thumbnail_url"`
	Subscribed       sql.NullBool `json:"subscribed"`
	CreatedAt        sql.NullTime `json:"created_at"`
	UpdatedAt        sql.NullTime `json:"updated_at"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
}

type IngestionChannelSnapshot struct {
	ID                uuid.UUID    `json:"id"`
	ChannelID         uuid.UUID    `json:"channel_id"`
	MeasuredAt        time.Time    `json:"measured_at"`
	SubscriptionCount int32        `json:"subscription_count"`
	CreatedAt         sql.NullTime `json:"created_at"`
}

type IngestionKeyword struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	FilterType  string         `json:"filter_type"`
	Pattern     string         `json:"pattern"`
	Enabled     sql.NullBool   `json:"enabled"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type IngestionSnapshotTask struct {
	VideoID        uuid.UUID `json:"video_id"`
	CheckpointHour int32     `json:"checkpoint_hour"`
	ScheduledAt    time.Time `json:"scheduled_at"`
}

type IngestionVideo struct {
	ID               uuid.UUID    `json:"id"`
	YoutubeVideoID   string       `json:"youtube_video_id"`
	ChannelID        uuid.UUID    `json:"channel_id"`
	YoutubeChannelID string       `json:"youtube_channel_id"`
	Title            string       `json:"title"`
	PublishedAt      time.Time    `json:"published_at"`
	CategoryID       int32        `json:"category_id"`
	ThumbnailUrl     string       `json:"thumbnail_url"`
	VideoUrl         string       `json:"video_url"`
	CreatedAt        sql.NullTime `json:"created_at"`
	UpdatedAt        sql.NullTime `json:"updated_at"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
}

type IngestionVideoSnapshot struct {
	ID                uuid.UUID    `json:"id"`
	VideoID           uuid.UUID    `json:"video_id"`
	CheckpointHour    int32        `json:"checkpoint_hour"`
	MeasuredAt        time.Time    `json:"measured_at"`
	ViewsCount        int64        `json:"views_count"`
	LikesCount        int64        `json:"likes_count"`
	SubscriptionCount int64        `json:"subscription_count"`
	Source            string       `json:"source"`
	CreatedAt         sql.NullTime `json:"created_at"`
}
