// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CheckVideoExists(ctx context.Context, youtubeVideoID string) (bool, error)
	CountChannels(ctx context.Context) (int64, error)
	CountVideosByChannel(ctx context.Context, channelID uuid.UUID) (int64, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) error
	CreateKeyword(ctx context.Context, arg CreateKeywordParams) error
	CreateSnapshotTask(ctx context.Context, arg CreateSnapshotTaskParams) error
	CreateVideo(ctx context.Context, arg CreateVideoParams) error
	CreateVideoSnapshot(ctx context.Context, arg CreateVideoSnapshotParams) error
	DeleteSnapshotTask(ctx context.Context, arg DeleteSnapshotTaskParams) error
	GetChannelByID(ctx context.Context, id uuid.UUID) (GetChannelByIDRow, error)
	GetChannelByYouTubeID(ctx context.Context, youtubeChannelID string) (GetChannelByYouTubeIDRow, error)
	GetKeywordByID(ctx context.Context, id uuid.UUID) (GetKeywordByIDRow, error)
	GetPendingSnapshotTasks(ctx context.Context, arg GetPendingSnapshotTasksParams) ([]IngestionSnapshotTask, error)
	GetVideoByID(ctx context.Context, id uuid.UUID) (GetVideoByIDRow, error)
	GetVideoByYouTubeID(ctx context.Context, youtubeVideoID string) (GetVideoByYouTubeIDRow, error)
	GetVideoSnapshotByVideoAndCheckpoint(ctx context.Context, arg GetVideoSnapshotByVideoAndCheckpointParams) (IngestionVideoSnapshot, error)
	ListActiveChannels(ctx context.Context) ([]ListActiveChannelsRow, error)
	ListActiveVideos(ctx context.Context, publishedAt time.Time) ([]ListActiveVideosRow, error)
	ListChannels(ctx context.Context, arg ListChannelsParams) ([]ListChannelsRow, error)
	ListEnabledKeywords(ctx context.Context) ([]ListEnabledKeywordsRow, error)
	ListSubscribedChannels(ctx context.Context) ([]ListSubscribedChannelsRow, error)
	ListVideoSnapshots(ctx context.Context, videoID uuid.UUID) ([]IngestionVideoSnapshot, error)
	ListVideosByChannel(ctx context.Context, arg ListVideosByChannelParams) ([]ListVideosByChannelRow, error)
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) error
}

var _ Querier = (*Queries)(nil)
