// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CheckVideoExists(ctx context.Context, youtubeVideoID string) (bool, error)
	CheckVideoGenreExists(ctx context.Context, arg CheckVideoGenreExistsParams) (bool, error)
	CountChannels(ctx context.Context) (int64, error)
	CountVideosByChannel(ctx context.Context, channelID uuid.UUID) (int64, error)
	// Audit Log queries
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	// Batch Job queries
	CreateBatchJob(ctx context.Context, arg CreateBatchJobParams) error
	CreateChannel(ctx context.Context, arg CreateChannelParams) error
	CreateChannelSnapshot(ctx context.Context, arg CreateChannelSnapshotParams) error
	// Genre queries
	CreateGenre(ctx context.Context, arg CreateGenreParams) error
	CreateKeyword(ctx context.Context, arg CreateKeywordParams) error
	CreateSnapshotTask(ctx context.Context, arg CreateSnapshotTaskParams) error
	CreateVideo(ctx context.Context, arg CreateVideoParams) error
	// Video Genre queries
	CreateVideoGenre(ctx context.Context, arg CreateVideoGenreParams) error
	CreateVideoSnapshot(ctx context.Context, arg CreateVideoSnapshotParams) error
	// YouTube Category queries
	CreateYouTubeCategory(ctx context.Context, arg CreateYouTubeCategoryParams) error
	DeleteSnapshotTask(ctx context.Context, arg DeleteSnapshotTaskParams) error
	DeleteVideoGenresByGenre(ctx context.Context, genreID uuid.UUID) error
	DeleteVideoGenresByVideo(ctx context.Context, videoID uuid.UUID) error
	GetBatchJobByID(ctx context.Context, id uuid.UUID) (IngestionBatchJob, error)
	GetChannelByID(ctx context.Context, id uuid.UUID) (GetChannelByIDRow, error)
	GetChannelByYouTubeID(ctx context.Context, youtubeChannelID string) (GetChannelByYouTubeIDRow, error)
	GetGenreByCode(ctx context.Context, code string) (IngestionGenre, error)
	GetGenreByID(ctx context.Context, id uuid.UUID) (IngestionGenre, error)
	GetKeywordByID(ctx context.Context, id uuid.UUID) (GetKeywordByIDRow, error)
	GetLatestChannelSnapshot(ctx context.Context, channelID uuid.UUID) (GetLatestChannelSnapshotRow, error)
	GetPendingSnapshotTasks(ctx context.Context, arg GetPendingSnapshotTasksParams) ([]IngestionSnapshotTask, error)
	GetVideoByID(ctx context.Context, id uuid.UUID) (GetVideoByIDRow, error)
	GetVideoByYouTubeID(ctx context.Context, youtubeVideoID string) (GetVideoByYouTubeIDRow, error)
	GetVideoSnapshotByVideoAndCheckpoint(ctx context.Context, arg GetVideoSnapshotByVideoAndCheckpointParams) (IngestionVideoSnapshot, error)
	GetYouTubeCategoryByID(ctx context.Context, id int32) (IngestionYoutubeCategory, error)
	ListActiveChannels(ctx context.Context) ([]ListActiveChannelsRow, error)
	ListActiveVideos(ctx context.Context, publishedAt time.Time) ([]ListActiveVideosRow, error)
	ListAssignableYouTubeCategories(ctx context.Context) ([]IngestionYoutubeCategory, error)
	ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]IngestionAuditLog, error)
	ListAuditLogsByResource(ctx context.Context, arg ListAuditLogsByResourceParams) ([]IngestionAuditLog, error)
	ListBatchJobsByTypeAndStatus(ctx context.Context, arg ListBatchJobsByTypeAndStatusParams) ([]IngestionBatchJob, error)
	ListChannelSnapshots(ctx context.Context, arg ListChannelSnapshotsParams) ([]ListChannelSnapshotsRow, error)
	ListChannels(ctx context.Context, arg ListChannelsParams) ([]ListChannelsRow, error)
	ListEnabledGenres(ctx context.Context) ([]IngestionGenre, error)
	ListEnabledKeywords(ctx context.Context) ([]ListEnabledKeywordsRow, error)
	ListGenres(ctx context.Context) ([]IngestionGenre, error)
	ListKeywordsByGenre(ctx context.Context, arg ListKeywordsByGenreParams) ([]ListKeywordsByGenreRow, error)
	ListKeywordsByGenreAndType(ctx context.Context, arg ListKeywordsByGenreAndTypeParams) ([]ListKeywordsByGenreAndTypeRow, error)
	ListRecentAuditLogs(ctx context.Context, limit int32) ([]IngestionAuditLog, error)
	ListRecentBatchJobs(ctx context.Context, arg ListRecentBatchJobsParams) ([]IngestionBatchJob, error)
	ListRunningBatchJobs(ctx context.Context) ([]IngestionBatchJob, error)
	ListSubscribedChannels(ctx context.Context) ([]ListSubscribedChannelsRow, error)
	ListVideoGenresByGenre(ctx context.Context, genreID uuid.UUID) ([]IngestionVideoGenre, error)
	ListVideoGenresByVideo(ctx context.Context, videoID uuid.UUID) ([]IngestionVideoGenre, error)
	ListVideoSnapshots(ctx context.Context, videoID uuid.UUID) ([]IngestionVideoSnapshot, error)
	ListVideosByChannel(ctx context.Context, arg ListVideosByChannelParams) ([]ListVideosByChannelRow, error)
	ListYouTubeCategories(ctx context.Context) ([]IngestionYoutubeCategory, error)
	SoftDeleteKeyword(ctx context.Context, arg SoftDeleteKeywordParams) error
	UpdateBatchJob(ctx context.Context, arg UpdateBatchJobParams) error
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) error
	UpdateGenre(ctx context.Context, arg UpdateGenreParams) error
	UpdateKeyword(ctx context.Context, arg UpdateKeywordParams) error
	UpdateYouTubeCategory(ctx context.Context, arg UpdateYouTubeCategoryParams) error
}

var _ Querier = (*Queries)(nil)
